using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace PlantersGUI
{
    static class Program
    {
        //Root form declaration.
        public static EntryForm entryForm;

        //Declare Experiment object.
        public static Experiment exp;

        //Program initialization.
        static Program()
        {
            //Autogenerated code. Cannot remove.
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);

            //Initialize entryForm. Must be done after above code.
            entryForm = new EntryForm();
        }
        
        //Thread attribute specification.
        [STAThread]



        //Entry point.
        static void Main()
        {
            //Run the application and display entryForm.
            Application.Run(entryForm);
        }
    }
}
